// ************** Subject Enum
const VALID_SUBJECT_LEVEL = ["ELEMENTARY", "MIDDLE", "HIGH"];
const VALID_SUBJECT_CATEGORY = ["CORE", "ELECTIVE", "SUPPORT"];
const VALID_SUBJECT_STATUS = ["ACTIVE", "ARCHIVED", "DELETED"];
const DEFAULT_SUBJECT_STATUS = "ACTIVE";
const VALID_SUBJECT_CONDITION_TYPE = ["TEST_SCORE", "AVERAGE"];
const SUBJECT = {
  VALID_LEVEL: VALID_SUBJECT_LEVEL,
  VALID_CATEGORY: VALID_SUBJECT_CATEGORY,
  VALID_STATUS: VALID_SUBJECT_STATUS,
  DEFAULT_STATUS: DEFAULT_SUBJECT_STATUS,
  VALID_CONDITION_TYPE: VALID_SUBJECT_CONDITION_TYPE,
};

// ************** Test Enum
const VALID_TEST_STATUS = ["DRAFT", "PUBLISHED", "ARCHIVED", "DELETED"];
const DEFAULT_TEST_STATUS = "DRAFT";

const VALID_GRADING_METHOD = ["MANUAL", "AUTO_GRADED"];
const DEFAULT_GRADING_METHOD = "MANUAL";

const TEST = {
  VALID_STATUS: VALID_TEST_STATUS,
  DEFAULT_STATUS: DEFAULT_TEST_STATUS,
  VALID_GRADING_METHOD: VALID_GRADING_METHOD,
  DEFAULT_GRADING_METHOD: DEFAULT_GRADING_METHOD,
};

// ************** Calcuation Result Enum
const CALCULATION_RESULT_STATUS = ["PUBLISHED", "ARCHIVED", "DELETED"];
const DEFAULT_CALCULATION_RESULT_STATUS = "PUBLISHED";

const CALCULATION_RESULT = {
  VALID_STATUS: CALCULATION_RESULT_STATUS,
  DEFAULT_STATUS: DEFAULT_CALCULATION_RESULT_STATUS,
};

// *************** Global Enum
const LOGIC_ENUM = ["AND", "OR"];
const OPERATOR_ENUM = ["EQ", "GTE", "GT", "LTE", "LT"];
const EXPECTED_OUTCOME_ENUM = ["PASS", "FAIL"];

// *************** EXPORT MODULE ***************

module.exports = {
  SUBJECT,
  TEST,
  CALCULATION_RESULT,
  LOGIC_ENUM,
  OPERATOR_ENUM,
  EXPECTED_OUTCOME_ENUM,
};
